const products = [
  {
    id: 11,
    brand: "ELFLIQ",
    name: "ELFLIQ Salt Nic 30ml",
    flavors: [
      { flavor: "Apple Peach 🍏🍑",                       flavorRu: "Apfel · Pfirsich" },
      { flavor: "Blueberry 🫐",                           flavorRu: "Blaubeere" },
      { flavor: "Cherry 🍒",                              flavorRu: "Kirsche" },
      { flavor: "Grape 🍇",                               flavorRu: "Traube" },
      { flavor: "Sour Apple 🍏⚡️",                       flavorRu: "Saurer Apfel" },
      { flavor: "Watermelon 🍉",                          flavorRu: "Wassermelone" },
      { flavor: "Apple Pear 🍏🍐",                        flavorRu: "Apfel · Birne" },
      { flavor: "Watermelon Cherry 🍉🍒",                 flavorRu: "Wassermelone · Kirsche" },
      { flavor: "Grape Cherry 🍇🍒",                      flavorRu: "Traube · Kirsche" },
      { flavor: "Strawberry Kiwi 🍓🥝",                   flavorRu: "Erdbeere · Kiwi" },
      { flavor: "Cherry Lemon Peach 🍒🍋🍑",              flavorRu: "Kirsche · Zitrone · Pfirsich" },
      { flavor: "Pink Lemonade 🍋🌸",                     flavorRu: "Pink Limonade" },
      { flavor: "Strawberry Cherry Lemon 🍓🍒🍋",         flavorRu: "Erdbeere · Kirsche · Zitrone" },
      { flavor: "Blueberry Raspberry Pomegranate 🫐🍓🍇", flavorRu: "Blaubeere · Himbeere · Granatapfel" },
    ],
    puffs: null,
    price: 10.99,
    salePrice: 10.50,
    nicotine: "30 ml · 50 mg/ml",
    note: "Жижа для вейпа",
    image: "images/elfliq-salt-nic.png",
    color: "#e91e8c"
  },
  {
    id: 1,
    brand: "Elfbar",
    name: "ELFA PRO Pod",
    flavors: [
      { flavor: "Raspberry Watermelon", flavorRu: "Himbeere · Wassermelone" },
      { flavor: "Mix Berries", flavorRu: "Beerenmix" },
    ],
    puffs: 600,
    price: 10.00,
    nicotine: "2 ml · 20 mg/ml",
    note: null,
    image: "images/elfbar-elfa-pro-raspberry-watermelon.jpg",
    color: "#9c27b0"
  },
  {
    id: 3,
    brand: "RandM",
    name: "RandM Tornado 9000",
    flavors: [
      { flavor: "Strawberry Ice", flavorRu: "Erdbeere · Eis" },
      { flavor: "Kiwi Passion Fruit Guava", flavorRu: "Kiwi · Maracuja · Guave" },
      { flavor: "Strawberry Raspberry Cherry Ice", flavorRu: "Erdbeere · Himbeere · Kirsche · Eis" },
      { flavor: "Blueberry Raspberry", flavorRu: "Blaubeere · Himbeere" },
      { flavor: "Watermelon Ice", flavorRu: "Wassermelone · Eis" },
      { flavor: "Mango Peach Ice", flavorRu: "Mango · Pfirsich · Eis" },
      { flavor: "Lemon Mint", flavorRu: "Zitrone · Minze" },
      { flavor: "Cola Ice", flavorRu: "Cola · Eis" },
      { flavor: "Passion Fruit Orange Guava", flavorRu: "Maracuja · Orange · Guave" },
      { flavor: "Grape Ice", flavorRu: "Traube · Eis" },
    ],
    puffs: 9000,
    price: 12.00,
    nicotine: "2 ml / 5 ml Nikotin",
    note: null,
    image: "images/randm-9000-all-flavors.jpg",
    color: "#7b2ff7"
  },
  {
    id: 7,
    brand: "Oxbar",
    name: "OXBAR NIC SWITCH",
    flavor: "Jewel Mint",
    flavorRu: "Minze",
    puffs: 35000,
    price: 14.99,
    nicotine: "0–5% einstellbar",
    note: "Nikotinstärke regelbar",
    image: "images/oxbar-nic-switch-jewel-mint.jpg",
    color: "#00bcd4"
  },
  {
    id: 8,
    brand: "Waspe",
    name: "WASPE AIVIOU 40000",
    flavor: "Kiwi Passion Fruit Guava + Strawberry Cherry",
    flavorRu: "Kiwi · Maracuja · Guave + Erdbeere · Kirsche",
    puffs: 40000,
    price: 14.99,
    nicotine: null,
    note: "2 Flavors in 1",
    image: "images/waspe-40000-kiwi-strawberry.jpg",
    color: "#455a64"
  },
];
