const products = [
  {
    id: 1,
    brand: "Elfbar",
    name: "ELFA PRO Pod",
    flavor: "Raspberry Watermelon",
    flavorRu: "Himbeere · Wassermelone",
    puffs: 600,
    price: 10.00,
    nicotine: "2 ml · 20 mg/ml",
    note: null,
    image: "images/elfbar-elfa-pro-raspberry-watermelon.jpg",
    color: "#e91e8c"
  },
  {
    id: 2,
    brand: "Elfbar",
    name: "ELFA PRO Pod",
    flavor: "Mix Berries",
    flavorRu: "Beerenmix",
    puffs: 600,
    price: 10.00,
    nicotine: "2 ml · 20 mg/ml",
    note: null,
    image: "images/elfbar-elfa-pro-mix-berries.jpg",
    color: "#9c27b0"
  },
  {
    id: 3,
    brand: "RandM",
    name: "RandM Tornado 9000",
    flavor: "Strawberry Ice",
    flavorRu: "Erdbeere · Eis",
    puffs: 9000,
    price: 13.00,
    nicotine: null,
    note: null,
    image: "images/randm-9000-strawberry-ice-purple.jpg",
    color: "#7b2ff7"
  },
  {
    id: 4,
    brand: "RandM",
    name: "RandM Tornado 9000",
    flavor: "Strawberry Ice",
    flavorRu: "Erdbeere · Eis",
    puffs: 9000,
    price: 13.00,
    nicotine: null,
    note: null,
    image: "images/randm-9000-strawberry-ice-pink.jpg",
    color: "#e91e8c"
  },
  {
    id: 5,
    brand: "RandM",
    name: "RandM Tornado 9000",
    flavor: "Kiwi Passion Fruit Guava",
    flavorRu: "Kiwi · Maracuja · Guave",
    puffs: 9000,
    price: 13.00,
    nicotine: null,
    note: "2 ml / 5 ml Nikotin",
    image: "images/randm-9000-kiwi-passion.jpg",
    color: "#4caf50"
  },
  {
    id: 6,
    brand: "RandM",
    name: "RandM Tornado 9000",
    flavor: "Strawberry Raspberry Cherry Ice",
    flavorRu: "Erdbeere · Himbeere · Kirsche · Eis",
    puffs: 9000,
    price: 13.00,
    nicotine: null,
    note: null,
    image: "images/randm-9000-strawberry-raspberry-cherry.jpg",
    color: "#ff5722"
  },
  {
    id: 7,
    brand: "Oxbar",
    name: "OXBAR NIC SWITCH",
    flavor: "Jewel Mint",
    flavorRu: "Minze",
    puffs: 35000,
    price: 14.99,
    nicotine: "0–5% einstellbar",
    note: "Nikotinstärke regelbar",
    image: "images/oxbar-nic-switch-jewel-mint.jpg",
    color: "#00bcd4"
  },
  {
    id: 8,
    brand: "Waspe",
    name: "WASPE AIVIOU 40000",
    flavor: "Kiwi Passion Fruit Guava + Strawberry Cherry",
    flavorRu: "Kiwi · Maracuja · Guave + Erdbeere · Kirsche",
    puffs: 40000,
    price: 14.99,
    nicotine: null,
    note: "2 Flavors in 1",
    image: "images/waspe-40000-kiwi-strawberry.jpg",
    color: "#455a64"
  },
  {
    id: 9,
    brand: "Waspe",
    name: "WASPE AIVIOU 40000",
    flavor: "Love 666 + Strawberry Raspberry Cherry",
    flavorRu: "Love 666 + Erdbeere · Himbeere · Kirsche",
    puffs: 40000,
    price: 14.99,
    nicotine: null,
    note: "2 Flavors in 1",
    image: "images/waspe-40000-love666-strawberry.jpg",
    color: "#37474f"
  },
  {
    id: 10,
    brand: "Waspe",
    name: "WASPE AIVIOU 40000",
    flavor: "Triple Melon Ice + Raspberry Watermelon",
    flavorRu: "Triple Melone · Eis + Himbeere · Wassermelone",
    puffs: 40000,
    price: 14.99,
    nicotine: null,
    note: "2 Flavors in 1",
    image: "images/waspe-40000-melon-raspberry.jpg",
    color: "#e65100"
  }
];
